@echo off
echo [Git AutoPush] Starting automatic push to GitHub...
echo [Git AutoPush] Adding all changes...
git add .
echo [Git AutoPush] Committing changes...
git commit -m "Auto commit - %date% %time%"
echo [Git AutoPush] Pushing to GitHub...
git push origin main
echo [Git AutoPush] Push completed successfully!
pause